In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


# 이미지와 CSV 파일 불러오기

In [ ]:
import numpy as np
import pandas as pd
from tensorflow import keras
from tensorflow.keras import layers
from sklearn.model_selection import KFold
import tensorflow as tf


path="/content/drive/MyDrive/petfinder-pawpularity-score"
train=pd.read_csv(path+'/train.csv')
test=pd.read_csv(path+'/test.csv')

In [ ]:
train["file_path"] = train["Id"].apply(lambda x:path +"/train/"+ x + ".jpg")
test["file_path"] = test["Id"].apply(lambda x:path +"/test/"+ x + ".jpg")

In [ ]:
test3_list= ["/content/00b151a572c9aabedf8cfce0fa18be25.jpg",
"/content/00c7b596627da7425b624d6b16c88a25.jpg",
"/content/0a05c55ca864b667d31c80ce2c68d6b3.jpg",
"/content/0ae5dc44eac23418d177f4cd11863aa6.jpg",
"/content/0b6052c68757d82e241bbb8c290c957d.jpg",
"/content/0b6b8b4c0d50b49d9ef0b5dc1f0d51d6.jpg",
"/content/0bea5f5e0274f3c3e9d621ea5a36fe74.jpg",
"/content/0c8c66ede77a34c7a9473eeb96a20f4b.jpg"]



In [ ]:
test4_list=["/content/1(2).png",
      "/content/2(2).png",
      "/content/3(2).png",
      "/content/4 (2).png",
      "/content/5 (2).png",
      "/content/6 (2).png",
      "/content/7 (2).png",
      "/content/8.png"
      ]

In [ ]:
train.sum

<bound method DataFrame.sum of                                     Id  ...                                          file_path
0     0007de18844b0dbbb5e1f607da0606e0  ...  /content/drive/MyDrive/petfinder-pawpularity-s...
1     0009c66b9439883ba2750fb825e1d7db  ...  /content/drive/MyDrive/petfinder-pawpularity-s...
2     0013fd999caf9a3efe1352ca1b0d937e  ...  /content/drive/MyDrive/petfinder-pawpularity-s...
3     0018df346ac9c1d8413cfcc888ca8246  ...  /content/drive/MyDrive/petfinder-pawpularity-s...
4     001dc955e10590d3ca4673f034feeef2  ...  /content/drive/MyDrive/petfinder-pawpularity-s...
...                                ...  ...                                                ...
9907  ffbfa0383c34dc513c95560d6e1fdb57  ...  /content/drive/MyDrive/petfinder-pawpularity-s...
9908  ffcc8532d76436fc79e50eb2e5238e45  ...  /content/drive/MyDrive/petfinder-pawpularity-s...
9909  ffdf2e8673a1da6fb80342fa3b119a20  ...  /content/drive/MyDrive/petfinder-pawpularity-s...
9910  fff19e2ce1171

In [ ]:
test3_list

['/content/00b151a572c9aabedf8cfce0fa18be25.jpg',
 '/content/00c7b596627da7425b624d6b16c88a25.jpg',
 '/content/0a05c55ca864b667d31c80ce2c68d6b3.jpg',
 '/content/0ae5dc44eac23418d177f4cd11863aa6.jpg',
 '/content/0b6052c68757d82e241bbb8c290c957d.jpg',
 '/content/0b6b8b4c0d50b49d9ef0b5dc1f0d51d6.jpg',
 '/content/0bea5f5e0274f3c3e9d621ea5a36fe74.jpg',
 '/content/0c8c66ede77a34c7a9473eeb96a20f4b.jpg']

In [ ]:
test4_list

['/content/1(2).png',
 '/content/2(2).png',
 '/content/3(2).png',
 '/content/4 (2).png',
 '/content/5 (2).png',
 '/content/6 (2).png',
 '/content/7 (2).png',
 '/content/8.png']

# 이미지 전처리
- 이미지 크기 128 x 128로 변환
- JPEG로 인코딩 된 이미지를 uint8 텐서로 디코딩
- 255로 나누어 픽셀값 정규화 



In [ ]:
image_size = 128
def preprocess(image_url):
    image_string = tf.io.read_file(image_url)
    image = tf.image.decode_jpeg(image_string, channels=3)
    image = tf.cast(image, tf.float32) / 255.0
    image = tf.image.resize(image, (image_size, image_size))
    return image
    

image.png


## 이미지 전처리(train, test) 

In [ ]:
x_train=[]
for i in train['file_path']:
    x1=preprocess(i)
    x_train.append(x1)

In [ ]:
test2=[]
for i in test['file_path']:
    x1=preprocess(i)
    test2.append(x1)
test2=np.array(test2)

In [ ]:
test3=[]
for i in test3_list:
    x1=preprocess(i)
    test3.append(x1)
test3=np.array(test3)

In [ ]:
test4=[]
for i in test4_list:
    x1=preprocess(i)
    test4.append(x1)
test4=np.array(test4)

In [ ]:
test3

array([[[[0.3815104 , 0.39525124, 0.19561888],
         [0.3299173 , 0.41156557, 0.17346814],
         [0.26769304, 0.35677084, 0.1734375 ],
         ...,
         [0.27161458, 0.3476103 , 0.14047182],
         [0.33259803, 0.40068936, 0.23952207],
         [0.21078432, 0.26960784, 0.14607844]],

        [[0.35683212, 0.4529565 , 0.20315564],
         [0.33019304, 0.42339155, 0.13593751],
         [0.33189338, 0.40341607, 0.20284927],
         ...,
         [0.3286765 , 0.39594057, 0.24931067],
         [0.3022212 , 0.36452207, 0.2544118 ],
         [0.17383578, 0.24148285, 0.14246324]],

        [[0.29336706, 0.41544116, 0.12892157],
         [0.342739  , 0.40896142, 0.22124693],
         [0.35609683, 0.40217525, 0.23037684],
         ...,
         [0.29143688, 0.35566792, 0.19882047],
         [0.27930453, 0.3459712 , 0.18126532],
         [0.2793352 , 0.34600186, 0.17477022]],

        ...,

        [[0.23543198, 0.33316484, 0.1426777 ],
         [0.16700368, 0.24972427, 0.09689032]

#모델 학습


In [ ]:
x_train=np.array(x_train)
y_train=train['Pawpularity']
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x_train,y_train,test_size=0.2)

In [ ]:
inputs=keras.Input(shape=(128,128,3))
x=inputs
x=keras.layers.Conv2D(filters=4,kernel_size=3,strides=2,padding='same',activation='relu')(x)
x=keras.layers.Conv2D(filters=8,kernel_size=3,strides=2,padding='same',activation='relu')(x)
x=keras.layers.Conv2D(filters=16,kernel_size=3,strides=2,padding='same',activation='relu')(x)
x=keras.layers.Conv2D(filters=32,kernel_size=3,strides=2,padding='same',activation='relu')(x)
x=keras.layers.Flatten()(x)
x=keras.layers.Dense(128, activation = "relu")(x)
x=keras.layers.Dropout(0.5)(x)
output = tf.keras.layers.Dense(1)(x)
model = tf.keras.Model(inputs=inputs, outputs=output)

In [ ]:
early_stop = tf.keras.callbacks.EarlyStopping(
    patience=5
    )
reduce_lr = tf.keras.callbacks.ReduceLROnPlateau(
    factor=0.1,
    patience=2, 
    min_lr=1e-9
    )
callbacks = [early_stop,reduce_lr]

In [ ]:
model.compile(loss='mse', optimizer='Adam', metrics=[tf.keras.metrics.RootMeanSquaredError(name="rmse"), "mae", "mape"])

In [ ]:
history = model.fit(x_train,y_train, epochs=25,batch_size=32,validation_data = (x_test,y_test),callbacks=callbacks)

Epoch 1/25
248/248 [==============================] - 11s 43ms/step - loss: 553.2623 - rmse: 23.5215 - mae: 17.4152 - mape: 79.9023 - val_loss: 412.2229 - val_rmse: 20.3033 - val_mae: 14.9723 - val_mape: 75.0617
Epoch 2/25
248/248 [==============================] - 11s 43ms/step - loss: 463.4741 - rmse: 21.5284 - mae: 16.0173 - mape: 78.5373 - val_loss: 410.9427 - val_rmse: 20.2717 - val_mae: 15.6268 - val_mape: 83.0203
Epoch 3/25
248/248 [==============================] - 11s 43ms/step - loss: 462.2291 - rmse: 21.4995 - mae: 15.9995 - mape: 77.5880 - val_loss: 442.1921 - val_rmse: 21.0284 - val_mae: 17.1672 - val_mape: 95.9761
Epoch 4/25
248/248 [==============================] - 11s 44ms/step - loss: 457.3344 - rmse: 21.3854 - mae: 15.9641 - mape: 78.5238 - val_loss: 414.1796 - val_rmse: 20.3514 - val_mae: 15.9626 - val_mape: 86.2995
Epoch 5/25
248/248 [==============================] - 11s 44ms/step - loss: 454.7607 - rmse: 21.3251 - mae: 15.9307 - mape: 78.5772 - val_loss: 406.3663

In [ ]:
cnn_pred=model.predict(test2)
cnn_pred

array([[35.783554],
       [35.222046],
       [35.40809 ],
       [34.731567],
       [34.97097 ],
       [35.24533 ],
       [35.24453 ],
       [35.120667]], dtype=float32)

In [ ]:
cnn_pred=model.predict(test3)
cnn_pred

array([[38.3366  ],
       [37.52552 ],
       [39.040993],
       [37.98592 ],
       [35.726402],
       [38.008667],
       [37.481163],
       [37.35485 ]], dtype=float32)

In [ ]:
cnn_pred=model.predict(test4)
cnn_pred

array([[35.24657 ],
       [35.06742 ],
       [37.04195 ],
       [35.18458 ],
       [35.996708],
       [37.4794  ],
       [35.052177],
       [35.587135]], dtype=float32)